### ISSUE TITLE
有关同步unpkg延迟的问题

### ISSUE THREAD

**Issue by CNFeffery** [cnpm/unpkg-white-list#158]
针对几天前就更新的资源，通过npmmirror访问依旧显示not found：

https://unpkg.com/dash-renderer@1.20.1/build/dash_renderer.min.js

https://registry.npmmirror.com/dash-renderer/1.20.1/files/build/dash_renderer.min.js

![image](https://github.com/cnpm/unpkg-white-list/assets/49147660/3f9ee31c-3f72-4a93-a8ff-47e2e54360cc)

**Comment by fengmk2** [comment]
后面可以到 https://npmmirror.com/package/dash-renderer 自行手动同步
![image](https://github.com/cnpm/unpkg-white-list/assets/156269/43a6a271-0755-433c-9593-a8ef4d54fb96)

已经同步好了。
https://cdn.npmmirror.com/packages/dash-renderer/syncs/2024/06/171153-666fb33386082b73d6110913.log
