### ISSUE TITLE
对白名单功能的一些建议

### ISSUE THREAD

**Issue by ao-x** [cnpm/unpkg-white-list#166]
1. 对未申请通过[unpkg-white-list](https://github.com/cnpm/unpkg-white-list)的包裹转跳unpkg
2. 过白进行问卷，实行实名与联系方式的填写（姓名、身份证号、邮箱、电话）。因为灰产有两种可能，一是使用他人信息，一是不过白，如果2-3次未联系上，或者联系上信息对不上的可以取消过白。

如果实现以上功能后预计会减少大量的灰产使用率，并保证此功能不会有一些潜在的风险，同时也保证了对正常用户的支持，像提出的.top域名与后缀问题可以得到有效解决。

这也是目前我个人对次功能的一些建议，也是我觉得目前一个比较好的解决方案。

**Comment by fengmk2** [comment]
只要敢来提 pr 的，并且 github 不是新注册的，基本就会通过了。

**Comment by fengmk2** [comment]
> 对未申请通过[unpkg-white-list](https://github.com/cnpm/unpkg-white-list)的包裹转跳unpkg

这个不行的，跳转也是禁止的。

**Comment by ao-x** [comment]
> 只要敢来提 pr 的，并且 github 不是新注册的，基本就会通过了。

感觉会造成https://x.com/fengmk2/status/1791498406923215020 类似问题的人员github注册的时间不会太短的

**Comment by ao-x** [comment]
> > 对未申请通过[unpkg-white-list](https://github.com/cnpm/unpkg-white-list)的包裹转跳unpkg
> 
> 这个不行的，跳转也是禁止的。

感觉可以https://registry.npmmirror.com/@aa/bb/x.x.x/files/ 重写到 https://unpkg.com/cc/dd@x.x.x/ x.x.x 可以为版本号等目前支持的版本号语义
