### ISSUE TITLE
白名单添加的scope已合并，文件访问失败

### ISSUE THREAD

**Issue by mdchun** [cnpm/unpkg-white-list#255]
## 问题
白名单 scope添加的@ztocwst，已合并，文件访问还是提示FORBIDDEN：
```[FORBIDDEN] "@ztocwst/rc-pro-materials" is not allow to unpkg files, see https://github.com/cnpm/unpkg-white-list```

地址：https://npmmirror.com/package/@ztocwst/rc-pro-materials/files
是有延迟吗？

**Comment by wangdaodao** [comment]
还没合并呢……

**Comment by mdchun** [comment]
> 还没合并呢……

嗯，我以为5分钟就都好了呢
