### ISSUE TITLE
referer from *.top domain was blocked

### ISSUE THREAD

**Issue by zhipenglin** [cnpm/unpkg-white-list#54]
之前一直用的一个资源，白名单也申请添加过了，现在资源报403 denied by Referer ACL 错误，请问是怎么回事啊

**Comment by fengmk2** [comment]
请问你的域名是那个？

**Comment by zhipenglin** [comment]
https://www.kne-union.top/ @fengmk2

**Comment by fengmk2** [comment]
@zhipenglin top 域名被黑灰尘利用太严重了，目前被拦截了，我得看看怎么单独加白名单。

**Comment by zhipenglin** [comment]
好的，麻烦了，整好了告诉我一下

**Comment by zhipenglin** [comment]
@fengmk2 top 域名可以用了吗？该怎么搞？

**Comment by zf1234d** [comment]
也许你应该把referrer改为same-origin，而不是申请白名单

**Comment by fengmk2** [comment]
@zhipenglin 目前没有办法，再等一段时间看看。

**Comment by fengmk2** [comment]
由于 top 域名太过宽松，被黑灰产大量使用，为了确保 npmmirror 可以持续运行，所以会继续跟域名的 referer 访问。

**Comment by zhipenglin** [comment]
> 由于 top 域名太过宽松，被黑灰产大量使用，为了确保 npmmirror 可以持续运行，所以会继续跟域名的 referer 访问。

现在这个有没有什么解决办法？除了换非top的域名？

**Comment by mobeicanyue** [comment]
> 由于 top 域名太过宽松，被黑灰产大量使用，为了确保 npmmirror 可以持续运行，所以会继续限制该域名的 referer 访问。

再整个 .top 白名单可行吗，因为很多人写博客因为便宜才买的 .top 域名

**Comment by fengmk2** [comment]
这个黑名单是静态配置，没法加白名单
