### ISSUE TITLE
[提问]规则生效时间

### ISSUE THREAD

**Issue by CNFeffery** [cnpm/unpkg-white-list#63]
请问成功向`package.json`中添加规则后，正常的生效时间是多久，比如昨天合进去的`feffery_antd_components`目前查看最近几个版本依然是403状态：

示例链接：
https://registry.npmmirror.com/feffery_antd_components/0.3.0-rc15/files/feffery_antd_components/feffery_antd_components.min.js

 截止目前的响应结果：
![image](https://github.com/cnpm/unpkg-white-list/assets/49147660/9c5c2e19-8602-47ec-86e6-434720dd6e59)

**Comment by fengmk2** [comment]
> "error": "[FORBIDDEN] \"feffery_antd_components@0.3.0-rc15\" not satisfies \"*\" to unpkg files, see https://github.com/cnpm/unpkg-white-list"

白名单生效了，但是 semver 匹配失败，我看看代码。

**Comment by fengmk2** [comment]
已修复
