### ISSUE TITLE
blocked

### ISSUE THREAD

**Issue by ao-x** [cnpm/unpkg-white-list#91]
今天访问一个资源，白名单也申请添加过了现在资源报"error": "blocked"，请问是怎么回事啊

**Comment by fengmk2** [comment]
@ao-x 发一下 url

**Comment by fengmk2** [comment]
压缩包不支持

**Comment by ao-x** [comment]
> 压缩包不支持

请问现在有哪些后缀的文件不支持

**Comment by fengmk2** [comment]
白名单后缀正在讨论中 https://github.com/cnpm/cnpmcore/issues/693
